In [5]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('bonus.csv')
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [7]:
df.shape

(1000, 5)

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

In [10]:
from sklearn.model_selection import train_test_split

X=df[['performance','years_of_experience','projects_completed']].values
y=df[['bonus']].values

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
X_train.shape,X_test.shape

((800, 3), (200, 3))

In [16]:
#converting to tensors
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

In [18]:
#Defining the Neural Network class

class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(3,1) #3 input features and output neurone
        )
    def forward(self,x):
        return self.network(x)

In [19]:
model=BonusPredictor()
criterion=nn.MSELoss()
optimizer=optim.SGD(model.parameters(),lr=0.001)

In [22]:
epochs = 5000

for epoch in range(epochs):
    #forward pass
    predictions=model(X_test_tensor)
    loss=criterion(predictions,y_test_tensor)
    #backward pass
    optimizer.zero_grad()
    loss.backward()
    #update weights
    optimizer.step()

    if(epoch+1)%100 == 0 :
        print(f' Epoch [{epoch +1}/{epochs}] ==> Loss : {loss.item():.2f}')

 Epoch [100/5000] ==> Loss : 1.81
 Epoch [200/5000] ==> Loss : 1.76
 Epoch [300/5000] ==> Loss : 1.72
 Epoch [400/5000] ==> Loss : 1.67
 Epoch [500/5000] ==> Loss : 1.63
 Epoch [600/5000] ==> Loss : 1.59
 Epoch [700/5000] ==> Loss : 1.55
 Epoch [800/5000] ==> Loss : 1.51
 Epoch [900/5000] ==> Loss : 1.47
 Epoch [1000/5000] ==> Loss : 1.44
 Epoch [1100/5000] ==> Loss : 1.40
 Epoch [1200/5000] ==> Loss : 1.37
 Epoch [1300/5000] ==> Loss : 1.33
 Epoch [1400/5000] ==> Loss : 1.30
 Epoch [1500/5000] ==> Loss : 1.26
 Epoch [1600/5000] ==> Loss : 1.23
 Epoch [1700/5000] ==> Loss : 1.20
 Epoch [1800/5000] ==> Loss : 1.17
 Epoch [1900/5000] ==> Loss : 1.14
 Epoch [2000/5000] ==> Loss : 1.11
 Epoch [2100/5000] ==> Loss : 1.08
 Epoch [2200/5000] ==> Loss : 1.06
 Epoch [2300/5000] ==> Loss : 1.03
 Epoch [2400/5000] ==> Loss : 1.00
 Epoch [2500/5000] ==> Loss : 0.98
 Epoch [2600/5000] ==> Loss : 0.95
 Epoch [2700/5000] ==> Loss : 0.93
 Epoch [2800/5000] ==> Loss : 0.91
 Epoch [2900/5000] ==> Loss :

In [24]:
#evaluating the model

model.eval()

with torch.no_grad():
    test_predictions=model(X_test_tensor)
    test_loss=criterion(test_predictions,y_test_tensor)

print(f'test loss : {test_loss.item():0.2f}')

test loss : 0.52


In [26]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [28]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [30]:
test_predictions[:3]

tensor([[189.9047],
        [150.5289],
        [113.0792]])

In [32]:
#to get the weights of the model

for name,value in model.named_parameters():
    print(f'Name :{name}, Values : {value}')

Name :network.0.weight, Values : Parameter containing:
tensor([[12.1200,  5.4658,  2.6470]], requires_grad=True)
Name :network.0.bias, Values : Parameter containing:
tensor([17.2826], requires_grad=True)
